services:
  mysql:
    image: "mysql:8.0"
    container_name: brainbuster-mysql
    environment:
      - "MYSQL_DATABASE=brainbusterdb"
      - "MYSQL_PASSWORD=rootroot"
      - "MYSQL_ROOT_PASSWORD=rootroot"
      - "MYSQL_USER=user"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local