spring:
  datasource:
    url: jdbc:mysql://mysql:3306/brainbusterdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true

jwt:
  secret: ${JWT_SECRET:dev-only-insecure-secret}
