name: Deploy Backend on master

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # NEW: compute lowercase owner and image name
      - name: Compute image name (lowercase owner)
        id: prep
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/brainbuster-backend" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build (skip tests if you want faster)
        run: mvn -B -DskipTests package

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/java/Dockerfile
          push: true
          tags: |
            ${{ steps.prep.outputs.IMAGE_NAME }}:latest
            ${{ steps.prep.outputs.IMAGE_NAME }}:${{ github.sha }}

      - name: SSH Deploy (port 3129)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 3129
          script: |
            set -e
            cd ${{ secrets.SERVER_WORKDIR }}
            export IMAGE_TAG=latest

            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            docker compose -f docker-compose.yml -f docker-compose.prod.yml pull app
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --remove-orphans
            docker system prune -af --volumes || true
